### ISSUE TITLE
Navigation menu

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#107]

**Comment by BonsaiOfHappiness** [comment]
Comments after review:

- [ ] If "active" menu point still close menu

**Comment by nhaesler** [comment]
Can you explain that comment?

Tried to reach you on Slack btw

**Comment by nhaesler** [comment]
@BonsaiOfHappiness

**Comment by BonsaiOfHappiness** [comment]
Mh, I'll tell you next time we speak :D

**Comment by nhaesler** [comment]
@BonsaiOfHappiness You didn't actually tell me the next we spoke :P
Also probably a duplicate of #101.

**Comment by BonsaiOfHappiness** [comment]
Let's ignore this for a while. It's not a "major bug" - Jakob and I will check for it again after the next update of dev.

**Comment by BonsaiOfHappiness** [comment]
@raubja Could you please show the steps to get to the navigation menu bug (orange link thingy)

**Comment by nhaesler** [comment]
That turned out to be a non-issue. Closing this in favor of #99.
