### ISSUE TITLE
SignUp: set button opacity to 100%

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#112]
![image](https://cloud.githubusercontent.com/assets/10120609/23061068/b45b821c-f500-11e6-839c-6711ebeac582.png)

**Comment by nhaesler** [comment]
If I set the alpha channel on the bottom nav to 1.0, it becomes black. I think we need a different colour definition for that?

**Comment by BonsaiOfHappiness** [comment]
Ah, I see. Please use this color code then :) 

#e6e6e6
