### ISSUE TITLE
StockSearch: "NaN"

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#116]
Either fix or replace with some other relevant data

![image](https://cloud.githubusercontent.com/assets/10120609/23062278/6dab9bea-f505-11e6-9552-0e835f44acb8.png)

**Comment by BonsaiOfHappiness** [comment]
I understand there's some issue with where we get the data for "most traded" from - if there's some kind of workaround to display exactly the same data as in the search that would be best.

**Comment by nhaesler** [comment]
No, I just have to add the value to the server response. I was just focusing on the client for now.

**Comment by BonsaiOfHappiness** [comment]
Alright, perfect :)

**Comment by nhaesler** [comment]
I fixed this in tradity/tradity-server@d17aa13
