### ISSUE TITLE
Number of shares in confirmation dialog is missing

### ISSUE THREAD

**Issue by addaleax** [tradity/tradity-client#12]
In `Do you want to trade {{amount}} of {{stockname}}?`, the amount is left blank.

Reported by @danielpodrazka.

**Comment by danielpodrazka** [comment]
Thanks for adding the issues,
The "amount" specifies only if it is 'share' or 'shares' based on $scope.amount but not the amount itself.
```
amount: gettextCatalog.getPlural($scope.amount, 'share', 'shares')
```
so something like this should work:
```
amount: gettextCatalog.getPlural($scope.amount, '{{$scope.amount}} share', '{{$scope.amount}} shares')
```
tradity-client/app/js/controllers/trade.js:41

**Comment by addaleax** [comment]
Should be fixed now :)
