### ISSUE TITLE
LeaderboardGroups: design issue

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#123]
maybe set min-height 50px + 3px * 2... + somehow need to fix the weird spacing issue between the placeholders/icons

![image](https://cloud.githubusercontent.com/assets/10120609/23063057/eb70fd9c-f508-11e6-958e-dc1309014071.png)

**Comment by nhaesler** [comment]
That's actually an issue on every of our lists, where the subvalue on the left side isn't provided. On that note – how should we handle long names now? Just cutting it off doesn't seem like such a good solution looking at the Immanuel-Kant-Gymnasium. It would probably just say “Immanuel-”.

**Comment by nhaesler** [comment]
Well, the ranking lists are probably mssing the buttons for expansion and so on. If we have those on every list, we could say that the names get expanded like they are now, when you click on expand.

**Comment by BonsaiOfHappiness** [comment]
Ok, can we put blank spaces if there's no subvalue (just as a quick fix - would do this properly later on).

You're right... that's a "fundamental" design flaw... let's limit it to an "appropriate" number of characters and then cut off... ideally so that we can limit the number of lines that result (on mobile)... I'd suggest something between 18 and 24 characters (looking at our examples)

**Comment by BonsaiOfHappiness** [comment]
Ah, that's a good idea... let's run with the "expand" idea for now

**Comment by nhaesler** [comment]
No blank spaces needed, the min-height you proposed is the appropriate fix for that.
