### ISSUE TITLE
Market orders are not being executed automatically on opening hours

### ISSUE THREAD

**Issue by danielpodrazka** [tradity/tradity-client#13]
I needed to delete the orders from the list and execute them manually.
Screenshot shows not executed orders whilst open market.
![tradity3](https://cloud.githubusercontent.com/assets/15668467/10993760/ac27e816-8471-11e5-987d-c4244d3ba9bc.png)

**Comment by BonsaiOfHappiness** [comment]
@danielpodrazka What was the time when you took the screenshot?
@addaleax Maybe it is because of the recent time change?

**Comment by danielpodrazka** [comment]
@BonsaiOfHappiness it was 10:11, 06.11.2015

**Comment by addaleax** [comment]
Should be fixed now
