### ISSUE TITLE
German characters are not decoded correctly in stock market names

### ISSUE THREAD

**Issue by danielpodrazka** [tradity/tradity-client#14]
It is impossible to search for stocks that have "ü", "ö", "ä" in their names. Examples:
![tradity2](https://cloud.githubusercontent.com/assets/15668467/10994118/784b4b66-8474-11e5-920b-39765f475ea3.png)
![tradity1](https://cloud.githubusercontent.com/assets/15668467/10994117/78488b06-8474-11e5-98ce-3d7768151f1a.png)

**Comment by addaleax** [comment]
This is… a rather interesting way to find out that the API of the Börse Frankfurt which backs our trading system finally switched to UTF-8. Thanks for reporting! (It will take a bit of time to adjust the names in our database, though).
