### ISSUE TITLE
Ability to invest more than 50% in one stock

### ISSUE THREAD

**Issue by danielpodrazka** [tradity/tradity-client#15]
If you invest more than once, the previous investment isn't considered, so you can invest more than 50% in one stock, which contradicts the 50% rule of competition.
Screenshot taken from user history : https://tradity.de/user/Lawe/history
![tradity4](https://cloud.githubusercontent.com/assets/15668467/10998053/95295192-8492-11e5-8c0d-a53458349493.png)

**Comment by addaleax** [comment]
Should be fixed now. Thanks for reporting!
