### ISSUE TITLE
Browser autocomplete in stock search is not disabled

### ISSUE THREAD

**Issue by addaleax** [tradity/tradity-client#16]
@hieutran Can you verify this and maybe take a look at it?

**Comment by hieutran** [comment]
OK, and I need a beta keys for testing purpose. Thank you!

**Comment by addaleax** [comment]
Just sent you an email with a bunch of new beta keys (You can use each one only once) :)

**Comment by hieutran** [comment]
@addaleax: Got it. Thank you!
