### ISSUE TITLE
Second questionnaire

### ISSUE THREAD

**Issue by addaleax** [tradity/tradity-client#19]
There will be a second questionnaire, analogously to the first one, which should be displayed to users after login/on page load. It would be cool if this could work by requesting `list-questionnaires` and testing whether there are any entries (if one is logged in, questionnaires that one has filled out will not be included in the result). This would have the additional benefit of letting users fill out the first questionnaire if they (for whatever reason) have not done so directly after the registration.

Things which will be different for the second questionnaire:

* Some questions accept multiple answers
* There will be possible answers with placeholders, e.g. `Other: ______`, where the user can fill in any freetext answer

CC @nhaesler @BonsaiOfHappiness

**Comment by hieutran** [comment]
Will the questionnaire modal be opened when a user, who did not complete "first" questionnaire, logged in?

**Comment by addaleax** [comment]
I guess so – that would have the additional advantage that there is no need to treat the questionnaires 1 and 2 specially, e.g. the client just checks *whether* there are unanswered questionnaires and then displays one of them

**Comment by addaleax** [comment]
I can upload the second questionnaire to the dev database later today, if you want that for testing

**Comment by hieutran** [comment]
Let me know when the database is ready :).

**Comment by addaleax** [comment]
Done; `list-questionnaires` should now also return questionnaire #2.

**Comment by addaleax** [comment]
@BonsaiOfHappiness Could you specify the deadline for this one again? iirc, it was around end of November

**Comment by BonsaiOfHappiness** [comment]
@addaleax @hieutran Yes, we want to display the second questionnaire starting November 29th. If we get it done sooner we could use the code to display the first questionnaire to those that didn't submit it the first time they saw it.

**Comment by BonsaiOfHappiness** [comment]
@hieutran What's the status? :)

**Comment by addaleax** [comment]
@BonsaiOfHappiness You can see the implementation on dev and, from Monday on, on stable. I have done some rough testing, but you may want to look at this in detail? Everything seems to work, though.
