### ISSUE TITLE
Overview over all comments for admins

### ISSUE THREAD

**Issue by addaleax** [tradity/tradity-client#21]
cc @mfun

**Comment by mfun** [comment]
Would also be nice to have a less flashy "commented deleted" note, because

Inspiration gives us https://github.com/nodejs/node/pull/4362, but it could be even more hidden..
Example for the recent situation: https://tradity.de/s/sally-bein-gymnasium/+pinboard

**Comment by mfun** [comment]
Would also be nice to have a less flashy "commented deleted" note, because

Inspiration gives us github pull requests, but it could be even more hidden..
Example for the recent situation: https://tradity.de/s/sally-bein-gymnasium/+pinboard

**Comment by addaleax** [comment]
@mfun @BonsaiOfHappiness Did you take a look at the event overview page? I pushed all recently developed features to stable today, i.e. you can take a look at it at https://tradity.de/admin/events. I know it looks bit weird right now, but I haven’t gotten feedback from any of you so far.

**Comment by mfun** [comment]
Thanks. This definitely is a nice overview. 
Regarding our responsibility for the content on tradity, it would be helpful to filter on which days there were comments posted. 
And maybe, when I've chosen a date and there a plenty of comments (like 18.02.15) there could be a simplified view to scroll faster through the comments (meaning the actual comment).
Thanks for this overview!

**Comment by addaleax** [comment]
> Regarding our responsibility for the content on tradity, it would be helpful to filter on which days there were comments posted. 

Not quite sure what you mean; If you are referring to a prettier version of `eventtime` (which is currently displayed in a format like 1454265500), that’s no problem.

And yes, probably a special view for comments only makes sense; Are there any other types of events (as listed on the page) that you may want a special overview for?

**Comment by addaleax** [comment]
+ Would you want/consider some kind of flagging system for comments, users, etc.?

**Comment by mfun** [comment]
A filter which shows me only the days where they actually were comments would be nice to have an overview for on which days we should take a closer look.
Something like a flagging system sounds reasonable.

**Comment by addaleax** [comment]
Ah, I get it – Should be feasible, I think.

**Comment by addaleax** [comment]
Will publish an update with comment stuff in the next days; You can preview it on dev. :)
