### ISSUE TITLE
random facts box

### ISSUE THREAD

**Issue by mfun** [tradity/tradity-client#23]
To help educating our users and giving them more insights, we would like to implement a little box - e.g. on the right side below or above the sponsor logos. 
Currently one person is working on the facts (starting with about 100), which shall be displayed randomly - one at a time.

**Comment by mfun** [comment]
What could be the size of the facts? In the examples we were at 100-300 characters. Could someone please give feedback on the preferred range of length? Thanks :)

**Comment by nhaesler** [comment]
That's mostly a question of design. Depending on when this feature and our new design are supposed to land, you should probably ask our new designer, who is not yet on GH afaik.

**Comment by BonsaiOfHappiness** [comment]
As soon as our new (web/ux) designer is onboarded we'll get back to this feature.

**Comment by nhaesler** [comment]
old client version. #79 for the new version
