### ISSUE TITLE
No securities found in search

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#31]
If the security hasn't been "opened" before there's no result in the search:
![screen shot 2016-01-28 at 1 44 57 pm](https://cloud.githubusercontent.com/assets/10120609/12644734/60caf512-c5c5-11e5-85ee-f5f848f3254f.png)

If the security has been opened, it's found but the name is not displayed:
![screen shot 2016-01-28 at 1 46 39 pm](https://cloud.githubusercontent.com/assets/10120609/12644760/9576ced0-c5c5-11e5-9e1c-e552c5b2465c.png)

**Comment by addaleax** [comment]
“opened” = ?

**Comment by BonsaiOfHappiness** [comment]
I held Amazon shares and clicked on the "trade button" there to get to the trade screen, which displayed the security correclty.
