### ISSUE TITLE
Use Börse Frankfurt push API for stock quotes

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#32]
Are the quotes (ask bid) supposed to be real time? If yes, I don't think they are. It seems more like we update every 5 mins or so. The quotes seen in the boerse-frankfurt.de tab are real time.

![screen shot 2016-01-28 at 1 58 17 pm](https://cloud.githubusercontent.com/assets/10120609/12645016/40ac53b4-c5c7-11e5-9652-ad810ea17211.png)

**Comment by addaleax** [comment]
Yes, we update every 5 minutes, due to the rather large underlying API change.

**Comment by BonsaiOfHappiness** [comment]
Okay, I see :)

**Comment by addaleax** [comment]
Is currently being tested on the dev server, the necessary code is there -> We should be able to publish this very soon
