### ISSUE TITLE
Maximum tradable amount not working

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#33]
Maximum amount tradable (should be 50% of total assets) is not displayed and (as it seems) also not considered as a condition for trade execution.

![screen shot 2016-01-28 at 2 04 08 pm](https://cloud.githubusercontent.com/assets/10120609/12645137/44dcc6f2-c5c8-11e5-9e43-fbd3e5687d42.png)

![screen shot 2016-01-28 at 2 04 18 pm](https://cloud.githubusercontent.com/assets/10120609/12645138/44dee8ec-c5c8-11e5-9da9-7c2d69a81cd3.png)

**Comment by addaleax** [comment]
You are aware that tradable amount = number of shares, not transaction volume?

**Comment by BonsaiOfHappiness** [comment]
ah sorry, I mean our "internal Tradity tradable amount/number of shares cap of 50% max of total assets" - not the other condition of "Frankfurt Stock Exchange tradable amount"

**Comment by addaleax** [comment]
Closing as this only applies for accounts with administrative privileges :)

**Comment by BonsaiOfHappiness** [comment]
Ohhhh - haha
