### ISSUE TITLE
(Sell) Limit Order not triggered/executed

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#35]
Even though the ask price was higher than the designated limit price the sell order was not triggered (though it shoul've been).

![screen shot 2016-01-28 at 2 33 54 pm](https://cloud.githubusercontent.com/assets/10120609/12645765/71aaeaf2-c5cc-11e5-93e5-6c85e9e48f44.png)

**Comment by BonsaiOfHappiness** [comment]
Probably this is connected to us updating quotes every 5 minutes? :)

**Comment by addaleax** [comment]
Are you sure that these orders should have been executed by now?

**Comment by BonsaiOfHappiness** [comment]
By now it's executed. I'll try to check and (if it's an issue) capture the instance.
