### ISSUE TITLE
tradity.de/GROUP link not correctly directing

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#36]
E. g. if I enter tradity.de/niebuell (while not logged in) --> it takes me to this link (which worked before we updated the registration):

![screen shot 2016-01-28 at 2 44 33 pm](https://cloud.githubusercontent.com/assets/10120609/12646016/01f09a02-c5ce-11e5-9994-1a4fffd5e1cf.png)

However, now we should adapt it. I guess it's not easy to make it work for the multi-step registration. So as a temporary solution we could just direct to the "normal registration page" https://tradity.de/register/step1

**Comment by addaleax** [comment]
IIRC, on the team meeting in December we agreed to drop tradity.de/[group name] links?

**Comment by BonsaiOfHappiness** [comment]
Yes, that was the initial idea for when we can replace it with a "better system". However, until then we'd like to have a "temporary solution". We don't need to auto-assign people with that solution, just make the "tradity.de/[group name] links" direct to either the registration, login or wordpress page :)

Is that possible?

**Comment by addaleax** [comment]
Yes, we could do that, but the general idea was to drop that namespace entirely – i.e. we can and should remove special handling for /[group name] links at all, which should lead users to the registration or login pages. (Please tell me you did not already print these links on some paper…? :D)

**Comment by BonsaiOfHappiness** [comment]
(we did, sorry) :D 

I thought that only the auto-assign was broken. But yes, I'm totally with you - for the future we need to come up with a good solution.

**Comment by addaleax** [comment]
> (we did, sorry) :D 

Meh – Still, I’d like to do everything as discussed previously -> So, no, I’m afraid that your proposed temporary solution will be permanent.

**Comment by BonsaiOfHappiness** [comment]
What does that mean? :) (regarding permanent)

**Comment by addaleax** [comment]
That means that:

1. You should stop printing out URLs we agreed do not exist :smile:
2. You should give us a list of URLs where it’s too late, and we install redirects to the registration page for them (and let all other previous group-registration URLs return 404s).

**Comment by BonsaiOfHappiness** [comment]
Sorry for the confusion, then. I didn't mean to decide that we abandon the "group url thing" - just, that it's a big issue we need to come up with a solution to (ideally, where we can omit the "extra links").

Does that mean though, that you already put in the effort to remove that function? :D

**Comment by addaleax** [comment]
No (well, except for the new registration effectively breaking these URLs), but as we said multiple times before, those URLs are a terrible idea all by themselves. Yes, we need a good way to provide a group on registration, but cluttering the tradity.de/[word] namespace with non-application stuff is not a good solution, not has it ever been one.

**Comment by BonsaiOfHappiness** [comment]
Yes, absolutely agree with you! 

What's the best solution for the current situation though? Can't we "redirect" all those /register/s/ type links to https://tradity.de/register/step1?

If not, the current situation shouldn't be too bad - in that case I'd jus add a register link. We've got more urgent issues.

**Comment by addaleax** [comment]
We’ll have to see whether links which pre-fill the group information on the registration page are actually something sustainable in the long run.

**Comment by BonsaiOfHappiness** [comment]
Yup - definitely. However, I guess we shouldn't work on that before the competition starts :D (since we don't have time)

**Comment by BonsaiOfHappiness** [comment]
@mfun so u can follow the discussion :)

**Comment by nhaesler** [comment]
old client version
