### ISSUE TITLE
bugs and changes to sign up form

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#39]
*(edited: turned this into todo list – anna)*
- [ ] All fields should be mandatory.
- [x] However, would like to add "prefer not to say" for gender,
- [x] have "no group" as an option for group at the top in the dropdown and
- [ ] a checkbox next to/beneath (we can fix design later) for "class/semester" that says "I'm not a student"... basically returning "no class/semester".

**Comment by BonsaiOfHappiness** [comment]
@addaleax

**Comment by nhaesler** [comment]
Thanks to uni and moving, I don't have a lot of time to look into this at the moment. So it'd be great, if someone else could take this off my plate.

**Comment by addaleax** [comment]
@BonsaiOfHappiness I’m somewhat afraid the “I’m not a student” checkbox can be *very* confusing with respect to choosing a group (i.e. if you check it, I’m not sure a lot of people will get that this *only* refers to the class/semester field).

**Comment by BonsaiOfHappiness** [comment]
Mh true, but it's technically feasible? Would propose a different "label" then: "This field does not apply for me" (or something similar)
What do you think? :)

**Comment by addaleax** [comment]
I think it might be the best solution to leave the field alone…

1. I think someone who filled out the “group” field probably will not skip this one (esp. since it is not very hard to fill out?)
2. Things like “no student”/“doesn’t apply” may make the registration form less overseeable, both to the user and to us programmers, since non-trivial code is necessary to keep both form fields coherent (Like: If the use clicks “doesn’t apply”, the text field should probably disabled; But what if the user already wrote something there? Should it be cleared? If we don’t disable the text field, what *does* happen when the checkbox is checked and there is text in the field? etc.)

**Comment by addaleax** [comment]
Btw, I published the changes I made so far to stable

**Comment by BonsaiOfHappiness** [comment]
1. Yes, but if they choose "no group" they would skip the next field, right?
2. I see - let's not do it then.

Let's simply make everything mandatory except and I'll adapt the message for that "class field" saying something like: you can input 0 for "no class"

**Comment by addaleax** [comment]
I get why you want to do this, but I still think that’s horrible UX. If you are 100 % sure that this is the right way, it’s feasible, of course

**Comment by mfun** [comment]
UX may be something we have to discuss - on the other hand we heard from proud TKs and LKs how many students they have in their school groups. From this point of view we reached this goal.

**Comment by addaleax** [comment]
@mfun Not sure what you’re pointing at – should we leave the “class/semester” field as it is right now, or are you in favour of any of @BonsaiOfHappiness’ proposed changes? :D

**Comment by mfun** [comment]
I am super happy that we can get an overview whether the user are in the right groups.
To be honest I have no concrete opinion regarding the other changes.

**Comment by addaleax** [comment]
@BonsaiOfHappiness Maybe a good way would be to just ask users who selected a group but did not enter a class whether that’s correct?

**Comment by BonsaiOfHappiness** [comment]
@mfun "communications gap" here? :D I thouhgt it's essential to push users to input a class. If that's not necessary please let us simply not make that field mandatory :D

Otherwise, I believe that your suggestion sounds pretty good.
> to just ask users who selected a group but did not enter a class whether that’s correct

**Comment by mfun** [comment]
@BonsaiOfHappiness sorry, I was with my thoughts at the school field. 
@addaleax Can you please tell me when in the admin tool the class segment is displayed. 
I will then comment here again after that :)

**Comment by addaleax** [comment]
Ok, I’ll close this then.

@mfun: Precisely now. :P

**Comment by mfun** [comment]
From the organizational point of view it is no big deal if <10% are not entering their class. 
For me it looks like it is currently around 1-3%.
