### ISSUE TITLE
Pick start and end times for ranking computation via date picker

### ISSUE THREAD

**Issue by addaleax** [tradity/tradity-client#4]
Users can pick start and end times for the ranking table, i.e. they can see which player was best in a given span of time. Currently, this is implemented using a drop-down where one can pick values like “Since week begin”, “Since 1 month”, etc. (This actually seems to be broken right now – possibly due to angular-ui/bootstrap#2156).

It would be nicer if both start and end time could be implemented using date pickers, allowing for much more flexible ranking views. `angular-ui` provides such a date picker, which is probably the best tool for implementing this.

cc @BonsaiOfHappiness

**Comment by addaleax** [comment]
The preliminary drop-down solution works again in the current master (cfc4e4eed46574d7767b55823510d409e4335203)

**Comment by hieutran** [comment]
Because of the Angular UI Datepicker [open issue](https://github.com/angular-ui/bootstrap/issues/1012), the "until" datepicker still has a display problem. I will try to fix it next day :)

**Comment by addaleax** [comment]
If that’s fine with you, I’ll merge your commit anyway – The issue seems like it’s not too hard to work around, and I’d like to apply some changes after your commit (I’ll explain it over at the PR/with inline comments here)
