### ISSUE TITLE
Total assets not displayed correctly

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#47]
![screen shot 2016-02-16 at 3 35 00 pm](https://cloud.githubusercontent.com/assets/10120609/13086914/b922cfe4-d4e5-11e5-8311-f1caacf1b5de.png)

Total Assets (Gesamt) should be around 99960€ (if one sums up the account and depot value) but somehow it's 89960€.

I've checked the transaction history and everything should be fine. Any ideas what's happening there? 

The user's name is "bonerusher". We've heard of similar events and it all seems to be the same "displaying mistake".

**Comment by addaleax** [comment]
@BonsaiOfHappiness Is this a permanent error? It can take a bit of time to update the total values of users.

**Comment by BonsaiOfHappiness** [comment]
Ok, you're right. It's not permanent. Thanks :dancer:
