### ISSUE TITLE
Issues after REST API setup

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#62]
*Important and urgent*
- [x] Executing trades not possible (prompts appear but trades are not executed/do not show up in unfilled orders/transaction history)
- [x] Held shares not visible
- [x] Feed not visible

*Not so urgent*
- [x] Joining groups not possible (after clicking on the button it turns "blue/confirmed" but one doesn't enter the group even after switching to other tabs or reloading the page) 
- [x] Translations for some messages are different now

**Comment by addaleax** [comment]
@BonsaiOfHappiness Which account? I don’t really want to trade on Sunday just for testing :)

**Comment by BonsaiOfHappiness** [comment]
@addaleax Tradity_Admin

**Comment by addaleax** [comment]
@BonsaiOfHappiness Could you check again?

**Comment by BonsaiOfHappiness** [comment]
@addaleax Yay, it works :D

**Comment by BonsaiOfHappiness** [comment]
@addaleax Executing trades still doesn't work, does it? (the prompts are fine now but the shares still don't show up in my "held shares"/the trade doesn't show up in transaction history)

**Comment by addaleax** [comment]
@BonsaiOfHappiness That was only a display problem – should be fixed now :)

**Comment by addaleax** [comment]
(i.e. the trades were actually entered into the database, just not displayed in your /depot tab)

**Comment by BonsaiOfHappiness** [comment]
Ohhh - then sorry for all the entries haha

**Comment by BonsaiOfHappiness** [comment]
Everything seems to be working really smoothly right now - props to you and the REST API thingy :D

**Comment by addaleax** [comment]
Closing this then :) You or anyone else can just create new issues if something should pop up (which it probably will)

**Comment by BonsaiOfHappiness** [comment]
@addaleax Could you check the "group entering" again please? It doesn't seem to work for me. After entering and refreshing I'm not in. I can't really see any errors apart from 304s (mainly loading images).

**Comment by addaleax** [comment]
@BonsaiOfHappiness Yep. Also, don’t be scared to create new issues even if you can tell that some things are more or less related. :)
