### ISSUE TITLE
Registration not working - 500 Internal Server Error

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#63]
In the second step of the registration on bhf.tradity.de (uni) I get an error and "nothing happens" after clicking on the signup button.

![screen shot 2016-03-29 at 1 43 34 pm](https://cloud.githubusercontent.com/assets/10120609/14106885/a230f924-f5b4-11e5-99c8-13d5de8ddca1.png)

`bhf.tradity.de/api/v1/register:1 POST https://bhf.tradity.de/api/v1/register 500 (Internal Server Error)`

**Comment by addaleax** [comment]
@BonsaiOfHappiness Is fixed as of tradity/tradity-server@7dfa5a09a1a1. `5xx` errors (or other errors where you can see that something is going wrong server-side) might be better off reported at the server repository. Also, a screenshot of the actual error message would maybe have been helpful (network tab of the developer tools, where you can display the contents of the individual failing requests). :)

**Comment by BonsaiOfHappiness** [comment]
@addaleax Thank you for fixing the bug. I'll keep that in mind - next time I'll report the error "correctly" :)

Would this have been the error message? 

`{code: 500, error: "TypeError: t.replace is not a function",…}
code: 500
error: "TypeError: t.replace is not a function"
stack: ""TypeError: t.replace is not a function\n    at /home/sotrade/stable/server/template-loader.js:93:15\n    at Array.forEach (native)\n    at /home/sotrade/stable/server/template-loader.js:91:30\n    at process._tickCallback (node.js:406:9)""`

**Comment by addaleax** [comment]
Yes. :D It did get reported via e-mail too, though.

And btw, you can post multi-line code snippets here by using triple backslashes like this:
```
`​``
Line 1
Line 2
`​``
```
:smile:
