### ISSUE TITLE
RD: leader board

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#67]
**How the first version should look like:**

The leader board shows a fixed number of the top users. It's updated in as short as possible (and reasonable) intervals. It's possible to modify the view through filtering and ranking:
- filter by group and sub-group (region and school/uni)
- filter by rank (i. e. only display top 100 users)
- rank by start-to-date performance (start of competition)
- rank by week-to-date performance

We may want to show leader boards on different screens and in different contexts:
- home screen (e. g. showing only the top 3 users)
- dedicated leader board screen
- group screen (e. g. showing the leader board of that group)

The leader board items consist of:
- rank 
- profile
- user name
- (user description in case the user is one of the top 3)
- (number of trades in case the user is one of the top 3)
- relevant metrics: relative and absolute performance
- group

**What may come in later stages:**
- display of rank movement (i. e. green and red icons showing up- or down-movement in leader board)
- further ranking parameters such as following and leading performance (social trading) or experience points (education section)

**Comment by nhaesler** [comment]
Some notes to myself on how to implement the group ranking:
- Build a two-dimensional array with cities on the first level and their respective schools on the second level
- Take the user ranking list and traverse it for every school, adding up their total values into an average total value for every school and city (three-level for-loop)
- flatten out the list of cities and schools, sort and show them
- Consider whether users are allowed to be a member of a city, but not of one of its schools. Those would have to counted as well.
