### ISSUE TITLE
RD: Stock search

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#71]
**How the first version should look like:**

A search bar that suggests stocks based on a text or ID (ISIN/WKN) input as the user types (comparable to the Google search). The suggestion items consist of:
- stock name
- current price
- WKN/ISIN

- [x] done

Hovering over a line item should evoke the display of more detailed information somewhere. Alternatively more information is only displayed when a stock is chosen/clicked.

Detailed information should include:
- [x] Current ask price
- [x] Current bid price
- [x] Number of maximum tradable shares

**What may come in later stages:**
- a stock chart

**Comment by nhaesler** [comment]
@BonsaiOfHappiness Can you clarify on the comment part? Don't we want that just in the stock details view?

**Comment by BonsaiOfHappiness** [comment]
Yes, you are right. We changed the design of this over time.
