### ISSUE TITLE
RD: Trade functionality

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#72]
**How the first version should look like:**

The user should be able to modify:
- The number of shares inteded to be traded (with an indication of maximum tradable number of shares) 
- The amount of money intended to be traded (with an indication of maximum tradable amount of money)
- Choose between buy and sell

Further functionality should include:
- real time translation of shares to amount of money and vice versa 
- real time warnings when tradable amount is exceeded displaying correct error message (not enough money, cap by competition rule, amount tradable on exchange exceeded)

**What may come in later stages:**
- Limit and stop orders
- Warnings of illiquidity

**Comment by BonsaiOfHappiness** [comment]
Comments after review:

- [ ] Link number of shares to be traded with Euros to be invested
- [ ] Consider renaming "stocks"... not perfectly understood

**Comment by nhaesler** [comment]
@BonsaiOfHappiness What exactly do you want to rename here?

**Comment by BonsaiOfHappiness** [comment]
It's ok for now; we'll go through the entire app for wording after everything is working fine.
