### ISSUE TITLE
RD: Login

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#73]
**How the first version should look like:**

- [x] Login via username/email and password.
- [x] Error handling with relevant messages.

**What may come in later stages:**
- multi-step login for better mobile UX

**Comment by nhaesler** [comment]
@BonsaiOfHappiness I need some information on how the error handling is supposed to work, especially from a design point of view. Keep in mind that the server doesn't mark either the username or password as wrong. We just get back a “Login failed” (this is intended behavior)

**Comment by BonsaiOfHappiness** [comment]
@nhaesler Alright, will get back to you regarding this tomorrow. What "error types" do we get? Only login failed (as in email/password combination is wrong) or do we also get something like "user not existing"?

**Comment by nhaesler** [comment]
@BonsaiOfHappiness As I wrote above, we just get a “Login failed”. This is standard security behavior to make guessing of usernames and passwords harder.

**Comment by BonsaiOfHappiness** [comment]
I see. Thx :)
