### ISSUE TITLE
Redirection from login to registration not working for uni.tradity.de

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#9]
Firefox 41.0.2

I get redirected to uni.tradity.de/register but not to /register/step1

It's working for tradity.de

**Comment by BonsaiOfHappiness** [comment]
@hieutran

**Comment by hieutran** [comment]
@addaleax Can you tell me which branch are currently deployed to uni.tradity.de?

**Comment by addaleax** [comment]
It’s `stable`; Should be the same as tradity.de. You can always check which commit the build was based on by checking the `TRADITY_BUILD_STAMP` variable, which contains the unix timestamp of the build and the current git HEAD commit. :)

**Comment by hieutran** [comment]
@addaleax thank you
@BonsaiOfHappiness I checked that and it's work for latest version of Safari and Chrome. I will check it in Firefox later because of Firefox is not available on my laptop.

**Comment by hieutran** [comment]
Tested again and It did not work with all of my browser :(.

**Comment by hieutran** [comment]
It did not happen in all browsers in my local version. So I can not understand why it only happened in uni.tradity.de version. Can @addaleax check the deployed code and give me some hints?

**Comment by addaleax** [comment]
Seems to have worked after manually running `bower update` on the server… weird, but I’m going to include that line in the `build.sh`, just in case something like that happens again.
