### ISSUE TITLE
RD: forgot password functionality

### ISSUE THREAD

**Issue by nhaesler** [tradity/tradity-client#90]
@BonsaiOfHappiness

**Comment by BonsaiOfHappiness** [comment]
@nhaesler Gesehen, mache mir Gedanken und melde mich :)

**Comment by nhaesler** [comment]
@BonsaiOfHappiness We could, for the time being, just let a dialog box pop up which asks for email/username. Would be really quick to implement.

**Comment by BonsaiOfHappiness** [comment]
Let's do that
